### ISSUE TITLE
Fluidity + VueJS

### ISSUE THREAD

**Issue by c9mb** [mattbrailsford/umbraco-fluidity#120]
I have a request for a complex product configuration process for public users of an Umbraco site, that requires the use of custom data entities.

Depending on options selected, the next step may require fetching new data for the option choices, etc etc.

For various reasons, we are not ready to go with Umbraco-8 at this point, so will be building on an existing Umbraco-7 base.

At first blush, I'm thinking... Fluidity + VueJS

Is there any experience with this mix, good, bad, right, wrong, tips, suggestions, recommendations?

**Comment by mattbrailsford** [comment]
Hi @c9mbundy 

Sounds like a good solution.

The reality is that for your front end, Fluidity doesn't enforce any restrictions, the job of Fluidity is really to provide you with a UI to manage data in the back office, so from a front end perspective, you can access the data however you want. 

Sounds like in your scenario, you'd want to create some API controlers to expose the data to your Vue front end, maybe also adding some kinda of cache so that you aren't constantly hitting the database. Those would probably be my two tips.

Matt

**Comment by c9mb** [comment]
Cheers. I guess that's essentially what I'm thinking too.  VueJS is going to need to make some sort of ajax-promise-call to an Umbraco controller, that will fetch & return the data. I've done this before for backoffice plugins, so I assume it will be similar, even if via different authentication, and I guess that getting the data created via fluidity is essentially just another data-type reference as far as the Umbraco API is concerned.
